insert into carreras (siglas, nombre, escuela) values
  ('ARQ', 'Arquitecto', 'Arquitectura, Arte y Diseño'),
  ('BGB', 'Licenciado en Negocios Internacionales', 'Negocios'),
  ('BIE', 'Ingeniero Industrial y de Sistemas', 'Ingeniería y Ciencias'),
  ('BME', 'Ingeniero en Mecatrónica', 'Ingeniería y Ciencias'),
  ('IAL', 'Ingeniero en Alimentos', 'Ingeniería y Ciencias'),
  ('IBT', 'Ingeniero en Biotecnología', 'Ingeniería y Ciencias'),
  ('IC', 'Ingeniero Civil', 'Ingeniería y Ciencias'),
  ('IDM', 'Ingeniero en Ciencia de Datos y Matemáticas', 'Ingeniería y Ciencias'),
  ('IDS', 'Ingeniero en Desarrollo Sustentable', 'Ingeniería y Ciencias'),
  ('IE', 'Ingeniero en Electrónica', 'Ingeniería y Ciencias'),
  ('IFI', 'Ingeniero Físico Industrial', 'Ingeniería y Ciencias'),
  ('IID', 'Ingeniero en Innovación y Desarrollo', 'Ingeniería y Ciencias'),
  ('IIS', 'Ingeniero Industrial y de Sistemas', 'Ingeniería y Ciencias'),
  ('IM', 'Ingeniero Mecánico', 'Ingeniería y Ciencias'),
  ('IMA', 'Ingeniero Mecánico Administrador', 'Ingeniería y Ciencias'),
  ('IMD', 'Ingeniero Biomédico', 'Ingeniería y Ciencias'),
  ('IMT', 'Ingeniero en Mecatrónica', 'Ingeniería y Ciencias'),
  ('INA', 'Ingeniero en Nanotecnología', 'Ingeniería y Ciencias'),
  ('IQ', 'Ingeniero Químico', 'Ingeniería y Ciencias'),
  ('IQA', 'Ingeniero Químico Administrador', 'Ingeniería y Ciencias'),
  ('IRS', 'Ingeniero en Robótica y Sistemas Digitales', 'Ingeniería y Ciencias'),
  ('ISD', 'Ingeniero en Sistemas Digitales y Robótica', 'Ingeniería y Ciencias'),
  ('ITC', 'Ingeniero en Tecnologías Computacionales', 'Ingeniería y Ciencias'),
  ('ITD', 'Ingeniero en Transformación Digital de Negocios', 'Ingeniería y Ciencias'),
  ('LAD', 'Licenciado en Arte Digital', 'Arquitectura, Arte y Diseño'),
  ('LAE', 'Licenciado en Estrategia y Transformación de Negocios', 'Negocios'),
  ('LAF', 'Licenciado en Finanzas', 'Negocios'),
  ('LBC', 'Licenciado en Biociencias', 'Medicina y Ciencias de la Salud'),
  ('LC', 'Licenciado en Comunicación', 'Humanidades y Educación'),
  ('LCPF', 'Licenciado en Contaduría Pública y Finanzas', 'Negocios'),
  ('LDE', 'Licenciado en Emprendimiento', 'Negocios'),
  ('LDI', 'Licenciado en Diseño', 'Arquitectura, Arte y Diseño'),
  ('LDO', 'Licenciado en Desarrollo de Talento y Cultura Organizacional', 'Negocios'),
  ('LEC', 'Licenciado en Economía', 'Ciencias Sociales y Gobierno'),
  ('LED', 'Licenciado en Derecho', 'Ciencias Sociales y Gobierno'),
  ('LEI', 'Licenciado en Innovación Educativa', 'Humanidades y Educación'),
  ('LEM', 'Licenciado en Mercadotecnia', 'Negocios'),
  ('LIN', 'Licenciado en Negocios Internacionales', 'Negocios'),
  ('LIT', 'Licenciado en Inteligencia de Negocios', 'Negocios'),
  ('LLE', 'Licenciado en Letras Hispánicas', 'Humanidades y Educación'),
  ('LNB', 'Licenciado en Nutrición y Bienestar Integral', 'Medicina y Ciencias de la Salud'),
  ('LPE', 'Licenciado en Periodismo', 'Humanidades y Educación'),
  ('LPS', 'Licenciado en Psicología Clínica y de la Salud', 'Medicina y Ciencias de la Salud'),
  ('LRI', 'Licenciado en Relaciones Internacionales', 'Ciencias Sociales y Gobierno'),
  ('LTM', 'Licenciado en Tecnología y Producción Musical', 'Humanidades y Educación'),
  ('LTP', 'Licenciado en Gobierno y Transformación Pública', 'Ciencias Sociales y Gobierno'),
  ('LUB', 'Licenciado en Urbanismo', 'Arquitectura, Arte y Diseño')
on conflict (siglas) do nothing;
